### ISSUE TITLE
Error build project Barnacle OCT

### ISSUE THREAD

**Issue by duonghb53** [lequanglien/Rust-Substrate-Issues#2]
I clone source code project Barnacle OCT:
https://github.com/octopus-network/barnacle
Then add my pallet-poe to project and build but get error.
Link my source code:
https://github.com/OCT-VBI-Substrate/OCT-VBI-course/tree/master/assignment-5/barnacle
![OCT_barnacle_err_build](https://user-images.githubusercontent.com/10292938/151291656-086f4b21-7af3-4cd4-9cf6-e37f0d414f4a.png)

**Comment by CocDap** [comment]
![image](https://user-images.githubusercontent.com/48429826/151292547-05667e26-c9d4-4fbd-9eac-50361974152c.png)

**Comment by CocDap** [comment]
Problem: some dependencies are imported in different branch or tag or version
Example: In pallets, define frame-support : monthly-2021, but in runtime, define frame-support: polkadot branch
Solution: Import the same branch or tag or version
